<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Iec61850Sim.Core\Iec61850Sim.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Reference Include="iec61850dotnet">
            <HintPath>..\..\ThirdPartyRefs\iec61850dotnet.dll</HintPath>
        </Reference>
        <Reference Include="SCLParser">
            <HintPath>..\..\ThirdPartyRefs\SCLParser.dll</HintPath>
        </Reference>
    </ItemGroup>

    <ItemGroup>
      <None Update="Config\Demo_Ed2.cfg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Config\Demo_Ed2.icd">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="rfc1006.cfg">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="MudBlazor" Version="9.2.0" />
    </ItemGroup>


</Project>
