FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build

WORKDIR /src

COPY Iec61850Sim.Web/ Iec61850Sim.Web/
COPY ThirdPartyRefs/ ThirdPartyRefs/

WORKDIR /src/Iec61850Sim.Web

RUN dotnet publish -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:10.0

WORKDIR /app

COPY --from=build /app/publish .
COPY ThirdPartyRefs/libiec61850.so /app/libiec61850.so
COPY ThirdPartyRefs/libiec61850.so.1.6.1 /app/libiec61850.so.1.6.1

EXPOSE 8080
EXPOSE 102

ENTRYPOINT ["dotnet", "Iec61850Sim.Web.dll"]