<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="iec61850dotnet">
      <HintPath>..\ThirdPartyRefs\iec61850dotnet.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
